### ISSUE TITLE
UbiquityStoreManager + Magical Record

### ISSUE THREAD

**Issue by leoru** [lhunath/UbiquityStoreManager#1]
Hi! I use MagicalRecord in my project, but icloud support not good.
I want to use your manager with MagicalRecord, but when i run my app on two devices i have different data. But icloud container is joint. Can you help me with my problem? Or can you make some tutorial for working with your code + MagicalRecord?

**Comment by lhunath** [comment]
Hey Kirill,

I'm afraid I don't have the time on my hands to sit down and debug an
application with you.  If you can describe both the problem and the
relevant environment/setup clearly and concretely in an email, I may be
able to give you some feedback, though.

I've never used MagicalRecord before.

Best of luck!

Maarten Billemont.
