### ISSUE TITLE
Example project is dead

### ISSUE THREAD

**Issue by zhigang1992** [lhunath/UbiquityStoreManager#10]
Really awesome job...

But, the example project.
Can't compile.
The xcdatamodel seemed corrupted from a commit about 3 months ago.

please fix it.

**Comment by lhunath** [comment]
Fixed in 59a0c1e8452ba1094fafdd1d8804a1edfe93347c

Please note that the example is not really exemplary code... it is inherited from iCloudStoreManager and its code is messy.
