### ISSUE TITLE
Typo in tryLoadCloudStore and tryLoadLocalStore

### ISSUE THREAD

**Issue by LaborEtArs** [lhunath/UbiquityStoreManager#12]
Hello!
Just stumbled across (what I think would be) a type in the aforementioned methods.
Shouldn't the lines
"// Make sure the store is still missing.
                if (![[psc persistentStores] count])
                    return;"
in both methods read
"// Make sure the store is still missing.
                if ([[psc persistentStores] count])
                    return;"?
Without '!'??
Greetings
 LaborEtArs

PS: I'm totally new to GitHub. If I did a massive mistake by opening an 'issue' for this or did any other dumb thing, just give me a note :-)

**Comment by lhunath** [comment]
Absolutely.  Thanks for spotting that copy/paste error.  Fixed in 27f074206d6a389c80e7c7c5503c33c4bf297435
