### ISSUE TITLE
didLoadStoreForCoordinator fires before moc is ready to use

### ISSUE THREAD

**Issue by stefankendall** [lhunath/UbiquityStoreManager#14]
On the latest commit (and I'm not sure when this broken from 0.1.0), if I start making Core Data requests in this delegate method, I get exceptions which I cannot reproduce reliable. If I delay a second after this method ends, I never observe the exceptions.

**Comment by lhunath** [comment]
Can you provide the code you use in didLoadStoreForCoordinator and the precise stack trace & details for the exception?  Potentially, stacks of other threads may also be useful (better yet, a symbolicated crash report)

**Comment by lhunath** [comment]
Can I close this issue or are you still experiencing exceptions?  If so, I need the actual exceptions.

**Comment by lhunath** [comment]
Closing due to lack of feedback
