### ISSUE TITLE
Notification if iCloud is disabled in Settings

### ISSUE THREAD

**Issue by MasterOP22** [lhunath/UbiquityStoreManager#16]
Hey,

i have a question or maybe an issue. I'm missing a notification in your StoreManager, if the USer want to enable iCloud over the cloudEnabled switch, but iCloud is disabled in settings. It could be very important to notify the user of my app that he doesn't use the iCloud after try to enable it.

**Comment by lhunath** [comment]
You could check to see if [[NSFileManager defaultManager] ubiquityIdentityToken] is nil.
