### ISSUE TITLE
App crash when we edit same records at 2 devices

### ISSUE THREAD

**Issue by jayantikatariya** [lhunath/UbiquityStoreManager#18]
App crashing when we edit any record at 2 devices and table has relationships with other tables.

**Comment by lhunath** [comment]
I'll need more details than "app crashing"...
1. Log output generated by USM,
2. Stack trace of all relevant threads.
3. Crash cause (eg. signal, exception, etc)

**Comment by jayantikatariya** [comment]
First of all thanks for quick reply.

Here I have attached file and also some log as inline.

Let me know if you need any more details.

Stack Trace

---

0     CoreFoundation                        0x2eacdf4b __exceptionPreprocess + 131
1     libobjc.A.dylib                       0x38f0e6af objc_exception_throw + 39
2     CoreFoundation                        0x2ea09667 -[__NSDictionaryM setObject:forKey:] + 819
3     CoreData                              0x2e9418ef -[PFUbiquityRecordImportConflict addObjectID:forRelationship:] + 147
4     CoreData                              0x2e941a8f -[PFUbiquityRecordImportConflict resolveMergeConflictForLogContent:previousSnapshot:andAncestorSnapshot:withOldVersion:andNewVersion:error:] + 363
5     CoreData                              0x2e94293b -[PFUbiquityRecordImportConflict resolveConflict:] + 3127
6     CoreData                              0x2e92b83f -[_PFUbiquityRecordImportOperation processObjects:withState:andImportContext:outError:] + 4611
7     CoreData                              0x2e926307 -[_PFUbiquityRecordImportOperation applyChangesFromStoreSaveSnapshot:withImportContext:withError:] + 1623
8     CoreData                              0x2e928797 -[_PFUbiquityRecordImportOperation main] + 9003
9     Foundation                            0x2f3fc7db -[__NSOperationInternal _start:] + 771
10   CoreData                               0x2e93367b -[_PFUbiquityRecordsImporter scheduleTransactionLogOperations:synchronous:error:] + 739
11   CoreData                               0x2e933e89 -[_PFUbiquityRecordsImporter schedulePendingLogs:error:] + 1373
12   CoreData                               0x2e9348e7 -[_PFUbiquityRecordsImporter discoverAndImportAllAvailableLogs:error:] + 1135
13   CoreData                               0x2e98acab -[PFUbiquitySetupAssistant sideLoadStore:error:] + 4311
14   CoreData                               0x2e98203d -[PFUbiquitySetupAssistant finishSetupForStore:error:] + 2297
15   CoreData                               0x2e9814e3 -[PFUbiquitySetupAssistant finishSetupWithRetry:] + 43
16   CoreData                               0x2e94cf53 __57-[PFUbiquitySwitchboardEntry executeBlockOnPrivateQueue:]_block_invoke + 59
17   libdispatch.dylib                      0x393f1d1b _dispatch_call_block_and_release + 11
18   libdispatch.dylib                      0x393f8273 _dispatch_queue_drain$VARIANT$mp + 375
19   libdispatch.dylib                      0x393f806b _dispatch_queue_invoke$VARIANT$mp + 43
20   libdispatch.dylib                      0x393f8ce1 _dispatch_root_queue_drain + 77
21   libdispatch.dylib                      0x393f8f59 _dispatch_worker_thread2 + 57
22   libsystem_pthread.dylib                0x39533dbf _pthread_wqthread + 299
23   libsystem_pthread.dylib                0x39533c84 start_wqthread + 8

Thanks
Jayanti

On 09-Nov-2013, at 7:14 pm, Maarten Billemont notifications@github.com wrote:

> I'll need more details than "app crashing"...
> 
> Log output generated by USM,
> Stack trace of all relevant threads.
> —
> Reply to this email directly or view it on GitHub.
> 
> Stack Trace
> 
> ---
> 
> 0     CoreFoundation                        0x2eacdf4b __exceptionPreprocess + 131
> 1     libobjc.A.dylib                       0x38f0e6af objc_exception_throw + 39
> 2     CoreFoundation                        0x2ea09667 -[__NSDictionaryM setObject:forKey:] + 819
> 3     CoreData                              0x2e9418ef -[PFUbiquityRecordImportConflict addObjectID:forRelationship:] + 147
> 4     CoreData                              0x2e941a8f -[PFUbiquityRecordImportConflict resolveMergeConflictForLogContent:previousSnapshot:andAncestorSnapshot:withOldVersion:andNewVersion:error:] + 363
> 5     CoreData                              0x2e94293b -[PFUbiquityRecordImportConflict resolveConflict:] + 3127
> 6     CoreData                              0x2e92b83f -[_PFUbiquityRecordImportOperation processObjects:withState:andImportContext:outError:] + 4611
> 7     CoreData                              0x2e926307 -[_PFUbiquityRecordImportOperation applyChangesFromStoreSaveSnapshot:withImportContext:withError:] + 1623
> 8     CoreData                              0x2e928797 -[_PFUbiquityRecordImportOperation main] + 9003
> 9     Foundation                            0x2f3fc7db -[__NSOperationInternal _start:] + 771
> 10   CoreData                               0x2e93367b -[_PFUbiquityRecordsImporter scheduleTransactionLogOperations:synchronous:error:] + 739
> 11   CoreData                               0x2e933e89 -[_PFUbiquityRecordsImporter schedulePendingLogs:error:] + 1373
> 12   CoreData                               0x2e9348e7 -[_PFUbiquityRecordsImporter discoverAndImportAllAvailableLogs:error:] + 1135
> 13   CoreData                               0x2e98acab -[PFUbiquitySetupAssistant sideLoadStore:error:] + 4311
> 14   CoreData                               0x2e98203d -[PFUbiquitySetupAssistant finishSetupForStore:error:] + 2297
> 15   CoreData                               0x2e9814e3 -[PFUbiquitySetupAssistant finishSetupWithRetry:] + 43
> 16   CoreData                               0x2e94cf53 __57-[PFUbiquitySwitchboardEntry executeBlockOnPrivateQueue:]_block_invoke + 59
> 17   libdispatch.dylib                      0x393f1d1b _dispatch_call_block_and_release + 11
> 18   libdispatch.dylib                      0x393f8273 _dispatch_queue_drain$VARIANT$mp + 375
> 19   libdispatch.dylib                      0x393f806b _dispatch_queue_invoke$VARIANT$mp + 43
> 20   libdispatch.dylib                      0x393f8ce1 _dispatch_root_queue_drain + 77
> 21   libdispatch.dylib                      0x393f8f59 _dispatch_worker_thread2 + 57
> 22   libsystem_pthread.dylib                0x39533dbf _pthread_wqthread + 299
> 23   libsystem_pthread.dylib                0x39533c84 start_wqthread + 8

Threads

---

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394baa8c mach_msg_trap + 20
1     CoreFoundation                        0x2ea987c3 __CFRunLoopServiceMachPort + 155
2     CoreFoundation                        0x2ea96f2f __CFRunLoopRun + 855
3     CoreFoundation                        0x2ea01c27 CFRunLoopRunSpecific + 523
4     CoreFoundation                        0x2ea01a0b CFRunLoopRunInMode + 107
5     GraphicsServices                      0x33728283 GSEventRunModal + 139
6     UIKit                                 0x312a5049 UIApplicationMain + 1137
7     Moon Invoice                          0x0007b353 0x00077000 + 17235

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394ba83c kevent64 + 24
1     libdispatch.dylib                     0x393faf9b _dispatch_mgr_thread$VARIANT$mp + 39

Thread: Unknown Name (Crashed)
0     libsystem_kernel.dylib                0x394cd1fc __pthread_kill + 8
1     libsystem_c.dylib                     0x3947dffd abort + 77
2     Moon Invoice                          0x001cfc2f 0x00077000 + 1412143
3     CoreFoundation                        0x2eace24f __handleUncaughtException + 579
4     libobjc.A.dylib                       0x38f0e90f _ZL15_objc_terminatev + 175
5     libc++abi.dylib                       0x387c31c7 _ZSt11__terminatePFvvE + 79
6     libc++abi.dylib                       0x387c2d2d __cxa_increment_exception_refcount + 1
7     libobjc.A.dylib                       0x38f0e7f7 objc_exception_rethrow + 43
8     CoreData                              0x2e981bdf -[PFUbiquitySetupAssistant finishSetupForStore:error:] + 1179
9     CoreData                              0x2e9814e3 -[PFUbiquitySetupAssistant finishSetupWithRetry:] + 43
10   CoreData                               0x2e94cf53 __57-[PFUbiquitySwitchboardEntry executeBlockOnPrivateQueue:]_block_invoke + 59
11   libdispatch.dylib                      0x393f1d1b _dispatch_call_block_and_release + 11
12   libdispatch.dylib                      0x393f8273 _dispatch_queue_drain$VARIANT$mp + 375
13   libdispatch.dylib                      0x393f806b _dispatch_queue_invoke$VARIANT$mp + 43
14   libdispatch.dylib                      0x393f8ce1 _dispatch_root_queue_drain + 77
15   libdispatch.dylib                      0x393f8f59 _dispatch_worker_thread2 + 57
16   libsystem_pthread.dylib                0x39533dbf _pthread_wqthread + 299

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394baa8c mach_msg_trap + 20
1     CoreFoundation                        0x2ea987c3 **CFRunLoopServiceMachPort + 155
2     CoreFoundation                        0x2ea96ee9 __CFRunLoopRun + 785
3     CoreFoundation                        0x2ea01c27 CFRunLoopRunSpecific + 523
4     CoreFoundation                        0x2ea01a0b CFRunLoopRunInMode + 107
5     Foundation                            0x2f3ef3db -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 255
6     Foundation                            0x2f440311 -[NSRunLoop(NSRunLoop) run] + 81
7     Moon Invoice                          0x001a25e5 0x00077000 + 1226213
8     Foundation                            0x2f4b1c87 __NSThread__main** + 1063
9     libsystem_pthread.dylib               0x39535c1d _pthread_body + 141
10   libsystem_pthread.dylib                0x39535b8f _pthread_start + 103

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394baa8c mach_msg_trap + 20
1     CoreFoundation                        0x2ea987c3 __CFRunLoopServiceMachPort + 155
2     CoreFoundation                        0x2ea96ee9 __CFRunLoopRun + 785
3     CoreFoundation                        0x2ea01c27 CFRunLoopRunSpecific + 523
4     CoreFoundation                        0x2ea4573b CFRunLoopRun + 99
5     CoreMotion                            0x2f0b8235 CLSF_thorntonUpdate_6x6 + 57045
6     libsystem_pthread.dylib               0x39535c1d _pthread_body + 141
7     libsystem_pthread.dylib               0x39535b8f _pthread_start + 103

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394baa8c mach_msg_trap + 20
1     CoreFoundation                        0x2ea987c3 **CFRunLoopServiceMachPort + 155
2     CoreFoundation                        0x2ea96ee9 __CFRunLoopRun + 785
3     CoreFoundation                        0x2ea01c27 CFRunLoopRunSpecific + 523
4     CoreFoundation                        0x2ea01a0b CFRunLoopRunInMode + 107
5     Foundation                            0x2f43c2f7 +[NSURLConnection(Loader) _resourceLoadLoop:] + 319
6     Foundation                            0x2f4b1c87 __NSThread__main** + 1063
7     libsystem_pthread.dylib               0x39535c1d _pthread_body + 141
8     libsystem_pthread.dylib               0x39535b8f _pthread_start + 103

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394cd440 __select + 20
1     libsystem_pthread.dylib               0x39535c1d _pthread_body + 141
2     libsystem_pthread.dylib               0x39535b8f _pthread_start + 103

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394cdc7c __workq_kernreturn + 8

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394cdc7c __workq_kernreturn + 8

Thread: Unknown Name
0     libsystem_kernel.dylib                0x394cdc7c __workq_kernreturn + 8

Crashed Registers

---

r12 0x148
r10 0x31828122
r11 0x18
cpsr    0x10
r4  0x6
r5  0x3c1000
r6  0x1637abb0
r7  0x3c0bf4
r0  0x0
r1  0x0
r2  0x0
r3  0xffffffff
sp  0x3c0be8
r8  0x31842db2
r9  0x3b344e30
pc  0x394cd1fc
lr  0x39536a33

**Comment by lhunath** [comment]
The actual exception and USM log output. :-)

**Comment by lhunath** [comment]
I still need the actual exception that occurred and USM's log output.

**Comment by jayantikatariya** [comment]
I sent crash log with file attachment did you got that one?

**Comment by lhunath** [comment]
Yes.  And it includes stack traces.  Please have a look at the GitHub issue if you're unsure what you sent.  I still need the actual exception and USM's log output.

**Comment by jayantikatariya** [comment]
Log is too large so can you provide your email id so I can send email there if possible to provide?

**Comment by lhunath** [comment]
Closing because this is a Core Data issue.
