### ISSUE TITLE
Use UBM for local data

### ISSUE THREAD

**Issue by CiraciNicolo** [lhunath/UbiquityStoreManager#21]
I'm developing an application that stores data with CoreData, the initial release should only use local data and no iCloud but in a near future (when the iPad version will be available) it will. 

The question is: can I use USM for local data until the iCloud sync is implemented? There is cloudEnabled property, but it can be helpful?

**Comment by lhunath** [comment]
You could; but there's not really much to gain from USM at that point.  All you're doing is using USM to create your PSC, which is really trivial for a local store.

Regardless, you'd be well set for enabling iCloud later.

cloudEnabled is NO by default, so as long as you don't provide an interface for toggling cloud on, you can just get started with USM and no extra setup.  Then, in the future, add a toggle in your app that calls one of the setCloudEnabled\* methods.
