### ISSUE TITLE
Use existing iCloud store

### ISSUE THREAD

**Issue by TheCrab-xx** [lhunath/UbiquityStoreManager#23]
Hi,
I don't understand how to use an existing iCloud store created by "device A" into  "device B" after user have "switched on" on "device B",
can you explain me with a little example?

Thanks in advance

**Comment by lhunath** [comment]
When you enable iCloud on the first device, USM creates a new cloud store by seeding it with your local store. If you have a pre-existing local store, you could even set it as USM's local store to facilitate integration with it. Now, you have a cloud store seeded by device A's data. Device B is still using its local store though. When you just enable iCloud on device B, it will start using the existing cloud data, which was A's old local data. If instead, you want to give B the option of using its own local data for the clod store instead, you'll need to get rid of the existing cloud data and recreate it with B's local store. There is API to do this, but the easiest way to implement this use case is by using the setCloudEnabledAndOverwriteCloudWithLocalIfConfirmed: convenience method. This will enable iCloud like normal if no cloud store exists yet. If one does exist, it will trigger the confirmation block. Here, you could pop a UIAlert or put some other logic to decide whether to keep the existing cloud store or throw it away and use the device's local store to seed one instead.

**Comment by TheCrab-xx** [comment]
How suggested, i used this piece of code after importing PearlAlert classes:

```
[[appDelegate ubiquityStoreManager] setCloudEnabledAndOverwriteCloudWithLocalIfConfirmed:^(void (^setConfirmationAnswer)(BOOL answer)) {

                        // The current store has sites, ask the user if he wants to copy them to the cloud

                        [PearlAlert showAlertWithTitle:@"Copy Sites To iCloud?"
                                               message:@"You can either switch to your old iCloud sites "
                         @"or overwrite them with your current sites."
                                             viewStyle:UIAlertViewStyleDefault initAlert:nil
                                     tappedButtonBlock:^(UIAlertView *alert, NSInteger buttonIndex) {
                                         if (buttonIndex == [alert cancelButtonIndex])
                                             setConfirmationAnswer( NO );
                                         if (buttonIndex == [alert firstOtherButtonIndex])
                                             setConfirmationAnswer( YES );
                                     }
                                           cancelTitle:@"Use Old" otherTitles:@"Overwrite", nil];
 }];
```

but it does't show me a confirmation alert.
where i'm wrong?

**Comment by lhunath** [comment]
You'll need to look at the USM logs to see what's happening.  Note that it only asks, as I explained, when a store already exists.

**Comment by TheCrab-xx** [comment]
Solved, it works great!

**Comment by lhunath** [comment]
Glad you got it to work, TheCrab-xx.
