### ISSUE TITLE
+entityForName: could not locate an NSManagedObjectModel for entity name 'Event''

### ISSUE THREAD

**Issue by bygons** [lhunath/UbiquityStoreManager#24]
I keep getting this error:
2013-11-20 09:04:36.100 iComplete[3919:70b](null)
2013-11-20 09:04:36.100 iComplete[3919:f03] UbiquityStoreManager: Loading store...
2013-11-20 09:04:36.103 iComplete[3919:f03] UbiquityStoreManager: Will load local store.
2013-11-20 09:04:36.108 iComplete[3919:f03] UbiquityStoreManager: Clearing stores...
2013-11-20 09:04:36.126 iComplete[3919:f03] UbiquityStoreManager: Will clear stores.  Notifying application to reset its UI.
2013-11-20 09:04:36.149 iComplete[3919:f03] UbiquityStoreManager: Loading store: icomplete.sqlite
2013-11-20 09:04:36.175 iComplete[3919:f03] UbiquityStoreManager: Successfully loaded local store.
2013-11-20 09:04:36.177 iComplete[3919:f03] UbiquityStoreManager: Finished loading local store (UbiquityStoreErrorCauseNoError).  Notifying application to refresh its UI.
2013-11-20 09:04:36.198 iComplete[3919:70b] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+entityForName: could not locate an NSManagedObjectModel for entity name 'Event''

The first "Null" is the NSLog in this code:

```
_manager = [[UbiquityStoreManager alloc] initStoreNamed:nil
                      withManagedObjectModel:[self managedObjectModel]
                               localStoreURL:[[self applicationDocumentsDirectory] URLByAppendingPathComponent:@"icomplete.sqlite"]
                         containerIdentifier:nil
                      additionalStoreOptions:nil
                                    delegate:self];


NSLog(@"%@",managedObjectContext.description);
```

The fetch I am trying to do is in another object but I transfer the context like this:

```
- (void) fetch {
    NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
    NSEntityDescription *entity = [NSEntityDescription entityForName:@"Event" inManagedObjectContext:[AppDelegate sharedAppDelegate].managedObjectContext];
    [fetchRequest setEntity:entity];

    // Create the sort descriptors array.
    NSSortDescriptor *authorDescriptor = [[NSSortDescriptor alloc] initWithKey:@"dueDate" ascending:YES];
    NSArray *sortDescriptors = [[NSArray alloc] initWithObjects:authorDescriptor, nil];
    [fetchRequest setSortDescriptors:sortDescriptors];

    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"(masterTaskID != nil)"];
    [fetchRequest setPredicate:predicate];

    NSError *error;
    self.events = [[managedObjectContext executeFetchRequest:fetchRequest error:&error] mutableCopy];

}
```

I am probably giving the context to the other object incorrectly but I can't figure out where.

**Comment by lhunath** [comment]
Try passing `nil` for the `withManagedObjectModel:`.  If that fixes it, the bug is in your `managedObjectModel` method.  You _do_ have an entity named `Event`, right?  If you're not making headway, log the model in use by `[AppDelegate sharedAppDelegate].managedObjectContext`.

**Comment by bygons** [comment]
I tried nil it still crashes. I then logged the context right before the fetch and it has a context object. It looks like the object is just not the one in my MOM. All this works with default (ie non cloud) core data code. Could my entitlements be off? My ubiquity container identifier is a static string $(TeamIdentifierPrefix)com..... While my iCloud key value store is $(TeamIdentifierPrefix)$(CFBundleIdentifier). 

Antonio

**Comment by lhunath** [comment]
This has nothing to do with objects.  It has something to do with your entity not being in the model.  ie. there is no Event in your model definition.  This has nothing to do with your managedObjectContext, nothing to do with iCloud or persistence.  Also, please log the actual model in use by the context.  It's clear that the context isn't nil.

Regardless, this is not a USM issue, this is a core data issue.

**Comment by lhunath** [comment]
It's important to understand the distinction between the following terms:
- Persistence Model
- Persistence Coordinator
- Persistence Object Context
- Persistence Store

Make sure you know what each distinct term means :-)

**Comment by bygons** [comment]
I agree it is not USM. I appreciate the quick responses! I will look at it it is something in my code.

Thanks!

Antonio
