### ISSUE TITLE
Question - What is the recommended approach for migrating in Ordered Sets

### ISSUE THREAD

**Issue by josephlord** [lhunath/UbiquityStoreManager#25]
I believe that iCloud doesn't support ordered sets. If I am using USM to migrate to using iCloud how do you suggest I handle them?

Do I need to initially migrate to a structure that replaces them and then activate iCloud using USM?

Sorry to ask here but I'm hoping that a quick answer from you will save me hours of experimenting and then it will be documented for other developers too.

Thanks!

**Comment by lhunath** [comment]
You'll definitely want to migrate that to an NSArray before loading the store in with USM.
