### ISSUE TITLE
Fallback Store Not Working

### ISSUE THREAD

**Issue by kdbdallas** [lhunath/UbiquityStoreManager#28]
According to the WWDC 2013 iCloud video (session 207) when the user can not access the cloud (say iCloud is having issues or they are offline) the Fallback Store should allow them to access the data that is stored locally from the last time they downloaded, and they can access that data, and even make changes to it, and when a connection comes back it will push up the changes.

The problem I am having is that if I disconnect from the internet then I do not get access to any of the data. It looks like I have no data.

In the 2013 video it says that Apple is taking control of handling the fallback store, so I am not sure if maybe you still have code from when they weren't handling it, or something???

For example it must now be stored in local storage and not in iCloud (in the app sandboxed is sandboxed)

**Comment by lhunath** [comment]
Please provide logs of USM loading your store when you have no connection.

**Comment by kdbdallas** [comment]
Seems to be working ok now. Thanks
