### ISSUE TITLE
Infinite Loop when iCloud not setup?

### ISSUE THREAD

**Issue by kdbdallas** [lhunath/UbiquityStoreManager#31]
When I reset my simulator or device and do not setup iCloud, when I run I seem to be getting an infinite loop USM with

```
Loading store...
Will load local store.
Clearing stores...
Will clear stores.  Notifying application to reset its UI.
Switching cloud disabled -> enabled
Loading store...
Cannot load cloud store: User is not logged into iCloud.  Falling back to local store.
```

Then it just keeps looping from that top "Will Load..." down those others and again, until it finally crashes.
Both simulator and device, both 32bit and 64bit, clean install of device even.

Screen shot of Xcode below and links to the logs and to the full list of the thread debug contents of the USM thread from Xcode on the shown crash.

![screen shot 2013-12-07 at 2 15 55 pm](https://f.cloud.github.com/assets/59203/1699173/b53e0398-5f86-11e3-8cc5-835448972602.png)

**Comment by kdbdallas** [comment]
Logs: http://pastebin.com/nu3Shs34
Threads: http://pastebin.com/L9zfgHed

**Comment by lhunath** [comment]
This is probably because you unconditionally setCloudEnabled in willLoadStore.  You may want to put that in an if block that tests manager.cloudAvailable.

**Comment by lhunath** [comment]
09111a7 now has a check for this condition; so you shouldn't even need the if now.

**Comment by kdbdallas** [comment]
I still get an infinite loop, just in a different spot now.

Now it crashes on line 1618
return self.cloudWasEnabled = [local boolForKey:USMCloudEnabledKey];

and the threads go back and forth this time just between:
cloudEnabled  (line 1618)
setCloudWasEnabled:   (line 1622)

The only log message was:

UbiquityStoreManager: Loading store...

**Comment by kdbdallas** [comment]
In fact, it now crashes in this same spot no matter if iCloud is enabled or not

**Comment by lhunath** [comment]
Bleh.  Cyclic dependency.  Try 0c35fe3

**Comment by kdbdallas** [comment]
Looking good. Thanks
