### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by rfunk82** [lhunath/UbiquityStoreManager#33]
I get the following error:  

'JRSwizzle.h' file not found

**Comment by kdbdallas** [comment]
Sounds like you didn't initialize the submodule.
Make sure when you checkout the project you specify to checkout submodules as well, or look at the project (say in GitHub) and see what project its using, checkout that project in a different place, and copy the files needed manually, however this can be error prone, so I would suggest doing it with the project.

If you are using something like Tower for git, when you checkout there is a checkmark to get submodules as well

**Comment by rfunk82** [comment]
Thanks  kdbdallas, works now!
