### ISSUE TITLE
ManagedObjectContext slow loading

### ISSUE THREAD

**Issue by TheCrab-xx** [lhunath/UbiquityStoreManager#34]
Using my app with iCloud enabled i get the following error 

+entityForName: nil is not a legal NSManagedObjectContext parameter searching for entity name....

I have to wait about 10 seconds before the ManagedObjectContext is loaded so do not get the error above.

Is there a way to avoid the error and allow the user to display data?

**Comment by lhunath** [comment]
Slow loading should only be a problem on the app's very first launch or on iOS 6.

But yes, your application definitely needs to handle the case where you have no MOC available.  How you do so is up to you, and the smarter you are about it design wise, the more user-friendly it will be.

Unless you are always seeing slow loading on iOS 7, this is not a USM issue.  If you think it is, please post timestamped USM logs.
