### ISSUE TITLE
UbiquityStoreManager with Dropbox support

### ISSUE THREAD

**Issue by TheCrab-xx** [lhunath/UbiquityStoreManager#38]
What is the best practice to backup data from iCloud to Dropbox and viceversa using UbiquityStoreManager?

**Comment by lhunath** [comment]
The best way to do that is to not do that.

Export your data in an application-specific way using a data format that you can parse back in and import as new objects into an empty store.  <a href="https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/ObjC/MPAppDelegate_Store.m#L654">Master Password uses .mpsites files</a> for this.
