### ISSUE TITLE
Using UbiquityStoreManager with multiple local PersistentStores

### ISSUE THREAD

**Issue by neilt** [lhunath/UbiquityStoreManager#39]
I am trying to use two different PersistentStores, but one PersistentStoreCoordinator and one ManagedObjectContext.  One PersistentStore would be a sqlite iCloud or local store (depending on the users choice) managed by UbiquityStoreManager and the other PersistentStore would always be a local core data sqlite store.

In researching this it appears the that the PersistentStoreCoordinator merges the ManagedObjectModels and that the only way to tell the PersistentStoreCoordinator that an added store only uses part of the merged ManagedObjectModel is to use configurations in the ManagedObjectModel.  However, in the 5 places where addPersistentStoreWithType: is executed in UbiquityStoreManager.m the configuration is always set to nil (which equates to the Default configuration and excludes using configurations.)

I can add the local core data sqlite store to the coordinator using the following delegate code:

``` Objective-c
- (void)ubiquityStoreManager:(UbiquityStoreManager *)manager 
  didLoadStoreForCoordinator:(NSPersistentStoreCoordinator *)coordinator
                     isCloud:(BOOL)isCloudStore
{
    NSPersistentStore *localStore = [coordinator persistentStoreForURL:[self myLocalStoreURL]];
    if (localStore == nil)
    {
        DDLogVerbose(@"Adding local store to store coordinator.");
        NSError *error = nil;
        [coordinator addPersistentStoreWithType:NSSQLiteStoreType
                                  configuration:localConfig
                                            URL:[self myLocalStoreURL]
                                        options:@{NSMigratePersistentStoresAutomaticallyOption: @YES, NSInferMappingModelAutomaticallyOption: @YES}
                                          error:&error];
}
```

But I can't figure out how to get UbiquityStoreManager to associate the correct model with the PersistentStore it manages.

So should UbiquityStoreManager.m be changed or is there another, maybe better, approach that I am not aware of?

**Comment by neilt** [comment]
Here is how I solved the problem.

``` objective-c
MBP:UbiquityStoreManager nt$ cat add_configuration.patch
diff --git a/UbiquityStoreManager/UbiquityStoreManager.h b/UbiquityStoreManager/UbiquityStoreManager.h
index 0b62b25..92f7bc6 100644
--- a/UbiquityStoreManager/UbiquityStoreManager.h
+++ b/UbiquityStoreManager/UbiquityStoreManager.h
@@ -385,6 +385,11 @@ __attribute__((deprecated));
  *  @param additionalStoreOptions Additional persistence options that the stores should be initialized with.
  *  @param delegate The application controller that will be handling the application's persistence responsibilities.
  */
+- (id)initStoreNamed:(NSString *)contentName withManagedObjectModel:(NSManagedObjectModel *)model modelConfiguration:(NSString *)modelConfiguration
+       localStoreURL:(NSURL *)localStoreURL
+ containerIdentifier:(NSString *)containerIdentifier additionalStoreOptions:(NSDictionary *)additionalStoreOptions
+            delegate:(id<UbiquityStoreManagerDelegate>)delegate;
+
 - (id)initStoreNamed:(NSString *)contentName withManagedObjectModel:(NSManagedObjectModel *)model localStoreURL:(NSURL *)localStoreURL
  containerIdentifier:(NSString *)containerIdentifier additionalStoreOptions:(NSDictionary *)additionalStoreOptions
             delegate:(id<UbiquityStoreManagerDelegate>)delegate;
diff --git a/UbiquityStoreManager/UbiquityStoreManager.m b/UbiquityStoreManager/UbiquityStoreManager.m
index 59a7a22..52bc364 100644
--- a/UbiquityStoreManager/UbiquityStoreManager.m
+++ b/UbiquityStoreManager/UbiquityStoreManager.m
@@ -131,6 +131,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {

 @property(nonatomic, copy) NSString *contentName;
 @property(nonatomic, strong) NSManagedObjectModel *model;
+@property(nonatomic, strong) NSString *modelConfiguration;
 @property(nonatomic, copy) NSString *containerIdentifier;
 @property(nonatomic, copy) NSDictionary *additionalStoreOptions;
 @property(nonatomic, readonly) NSString *storeUUID;
@@ -169,8 +170,12 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {
         NSLog( @"UbiquityStoreManager: Warning: Failed to swizzle, won't be able to detect desync issues.  Cause: %@", error );
 }

-- (id)initStoreNamed:(NSString *)contentName withManagedObjectModel:(NSManagedObjectModel *)model localStoreURL:(NSURL *)localStoreURL
- containerIdentifier:(NSString *)containerIdentifier additionalStoreOptions:(NSDictionary *)additionalStoreOptions
+- (id)initStoreNamed:(NSString *)contentName
+withManagedObjectModel:(NSManagedObjectModel *)model
+  modelConfiguration:(NSString *)modelConfiguration
+       localStoreURL:(NSURL *)localStoreURL
+ containerIdentifier:(NSString *)containerIdentifier
+additionalStoreOptions:(NSDictionary *)additionalStoreOptions
             delegate:(id<UbiquityStoreManagerDelegate>)delegate {

     if (!(self = [super init]))
@@ -180,6 +185,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {
     _delegate = delegate;
     _contentName = contentName == nil? USMCloudContentName: contentName;
     _model = model == nil? [NSManagedObjectModel mergedModelFromBundles:nil]: model;
+    _modelConfiguration = modelConfiguration;
     if (!localStoreURL)
         localStoreURL = [[[self URLForApplicationContainer]
                 URLByAppendingPathComponent:[self localContentName] isDirectory:NO]
@@ -224,6 +230,14 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {
     return self;
 }

+- (id)initStoreNamed:(NSString *)contentName withManagedObjectModel:(NSManagedObjectModel *)model localStoreURL:(NSURL *)localStoreURL
+ containerIdentifier:(NSString *)containerIdentifier additionalStoreOptions:(NSDictionary *)additionalStoreOptions
+            delegate:(id<UbiquityStoreManagerDelegate>)delegate {
+    
+    return [self initStoreNamed:contentName withManagedObjectModel:model modelConfiguration:nil
+           localStoreURL:localStoreURL containerIdentifier:containerIdentifier additionalStoreOptions:additionalStoreOptions delegate:delegate];
+}
+
 - (void)dealloc {

     // Stop listening for store changes.
@@ -1042,7 +1056,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {

         NSAssert([self.persistentStoreCoordinator.persistentStores count] == 0, @"PSC should have no stores before trying to load one.");
         [self log:@"Loading store: %@", [targetStoreURL lastPathComponent]];
-        if (![self.persistentStoreCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:nil
+        if (![self.persistentStoreCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:self.modelConfiguration
                                                                      URL:targetStoreURL options:targetStoreOptions
                                                                    error:&error])
             [self error:error cause:IfOut(cause, UbiquityStoreErrorCauseOpenActiveStore)
@@ -1139,7 +1153,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {

                 // Add the store to migrate.
                 NSPersistentStore *migrationStore = [self.persistentStoreCoordinator
-                        addPersistentStoreWithType:NSSQLiteStoreType configuration:nil
+                        addPersistentStoreWithType:NSSQLiteStoreType configuration:self.modelConfiguration
                                                URL:migrationStoreURL options:migrationStoreOptions
                                              error:&error];
                 if (!migrationStore) {
@@ -1204,7 +1218,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {
     // Open migration store.
     NSError *error = nil;
     NSPersistentStoreCoordinator *migrationCoordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:self.model];
-    NSPersistentStore *migrationStore = [migrationCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:nil
+    NSPersistentStore *migrationStore = [migrationCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:self.modelConfiguration
                                                                                      URL:migrationStoreURL options:migrationStoreOptions
                                                                                    error:&error];
     if (!migrationStore) {
@@ -1215,7 +1229,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {

     // Open target store.
     NSPersistentStoreCoordinator *targetCoordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:self.model];
-    NSPersistentStore *targetStore = [targetCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:nil
+    NSPersistentStore *targetStore = [targetCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:self.modelConfiguration
                                                                                URL:targetStoreURL options:targetStoreOptions
                                                                              error:&error];
     if (!targetStore) {
@@ -1420,7 +1434,7 @@ extern NSString *NSStringFromUSMCause(UbiquityStoreErrorCause cause) {
             NSMutableDictionary *rebuildOptions = [options mutableCopy];
             rebuildOptions[NSPersistentStoreRebuildFromUbiquitousContentOption] = @YES;
             if (![[[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:self.model]
-                    addPersistentStoreWithType:NSSQLiteStoreType configuration:nil
+                    addPersistentStoreWithType:NSSQLiteStoreType configuration:self.modelConfiguration
                                            URL:cloudStoreURL options:rebuildOptions error:&error]) {
                 [self error:error cause:UbiquityStoreErrorCauseDeleteStore context:cloudStoreURL];
                 return NO;
```

**Comment by lhunath** [comment]
Yes, I made a similar commit yesterday; didn't get around to pushing it yet.

**Comment by lhunath** [comment]
see 9ef87ba2a09630bd5977da288ec701789e9e5c39

**Comment by neilt** [comment]
Thanks,
Neil

**Comment by Kyrill76** [comment]
Hi,

I’m trying to work with two persistent stores, one that can be synced with iCloud, depending on the user’s choice, and another that will never be synced.
I made one data model, and added two configurations to that model, “Synced” configuration, which includes all the entities that I want synced if the user uses iCloud, and “NotSynced”, which includes the one entity that I don’t want synced.

In my AppDelegate, I initialize the UbiquityStoreManager in "application didFinishLaunchingWithOptions" with this call :

```
_ubiquityStoreManager = [[UbiquityStoreManager alloc] initStoreNamed:nil withManagedObjectModel:nil localStoreURL:nil
                                                 containerIdentifier:nil storeConfiguration:@"Synced" storeOptions:nil delegate:self];
```

Then I use this to add the “NotSynced” store to the coordinator :

```
-(void)ubiquityStoreManager:(UbiquityStoreManager *)manager didLoadStoreForCoordinator:(NSPersistentStoreCoordinator *)coordinator
                 isCloud:(BOOL)isCloudStore {
NSManagedObjectContext *moc = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSMainQueueConcurrencyType];
moc.persistentStoreCoordinator = coordinator;
moc.mergePolicy = NSMergeByPropertyObjectTrumpMergePolicy;

NSURL *applicationSupportURL = [[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory
                                                                       inDomains:NSUserDomainMask] lastObject];
NSString *contentName = @"NotSyncedStore";
NSURL *notSyncedStoreUrl = [[applicationSupportURL
                                             URLByAppendingPathComponent:contentName isDirectory:NO]
                                            URLByAppendingPathExtension:@"sqlite"];

NSPersistentStore *notSyncedStore = [coordinator persistentStoreForURL:notSyncedStoreUrl];
if (notSyncedStore == nil)
{
    NSLog(@"Adding not synced store to store coordinator.");
    NSError *error = nil;
    [coordinator addPersistentStoreWithType:NSSQLiteStoreType
                              configuration:@"NotSynced"
                                        URL:notSyncedStoreUrl
                                    options:@{NSMigratePersistentStoresAutomaticallyOption: @YES, NSInferMappingModelAutomaticallyOption: @YES}
                                      error:&error];
}

_managedObjectContext = moc;

dispatch_async( dispatch_get_main_queue(), ^{
    [cloudContentCorruptedAlert dismissWithClickedButtonIndex:[cloudContentCorruptedAlert cancelButtonIndex] animated:YES];
    [handleCloudContentWarningAlert dismissWithClickedButtonIndex:[handleCloudContentWarningAlert cancelButtonIndex] animated:YES];
} );
}
```

If I don’t make any changes to the UbiquityStoreManager files, here’s the error that I get when an app receives existing data from iCloud for the first time (I included the full log) :

> 2014-09-07 19:32:02.291 MyApp[701:60b] iCloud store chosen
> 
> 2014-09-07 19:32:02.293 MyApp[701:1803] UbiquityStoreManager: Switching cloud disabled -> enabled
> 
> 2014-09-07 19:32:02.294 MyApp[701:1803] UbiquityStoreManager: Reloading store...
> 
> 2014-09-07 19:32:02.297 MyApp[701:1803] UbiquityStoreManager: Will load cloud store.
> 
> 2014-09-07 19:32:02.298 MyApp[701:1803] UbiquityStoreManager: Clearing stores...
>  
> 2014-09-07 19:32:02.303 MyApp[701:1803] UbiquityStoreManager: Will clear stores.  Notifying application to reset its UI.
>  
> 2014-09-07 19:32:07.800 MyApp[701:1803] UbiquityStoreManager: Loading cloud store: BF2BD678-DA6D-411B-BB82-335692E92098, v1 (definite).
>  
> 2014-09-07 19:32:07.801 MyApp[701:1803] UbiquityStoreManager: [DEBUG] migrationStoreURL: (null)
>  
> 2014-09-07 19:32:07.802 MyApp[701:1803] UbiquityStoreManager: [DEBUG] migrationStoreOptions: {
>  
> NSInferMappingModelAutomaticallyOption = 1;
>  
> NSMigratePersistentStoresAutomaticallyOption = 1;
>  
> NSReadOnlyPersistentStoreOption = 1;
>  
> }
>  
> 2014-09-07 19:32:08.332 MyApp[701:1803] UbiquityStoreManager: [DEBUG] cloudSafeForSeeding: 0
>  
> 2014-09-07 19:32:08.690 MyApp[701:1803] UbiquityStoreManager: [DEBUG] Will NOT migrate to cloud store from: MyAppUbiquityStore.sqlite (strategy: 2).
>  
> 2014-09-07 19:32:08.870 MyApp[701:1803] UbiquityStoreManager: Loading store: BF2BD678-DA6D-411B-BB82-335692E92098.sqlite
>  
> 2014-09-07 19:32:09.035 MyApp[701:1803] -[PFUbiquitySwitchboardEntryMetadata setUseLocalStorage:](771): CoreData: Ubiquity:  mobile~EC62D12B-BC39-4A48-87D4-604726F9772D:BF2BD678-DA6D-411B-BB82-335692E92098
>  
> Using local storage: 1
>  
> 2014-09-07 19:32:09.574 MyApp[701:1803] UbiquityStoreManager: Successfully loaded cloud store.
>  
> 2014-09-07 19:32:11.760 MyApp[701:1803] UbiquityStoreManager: Finished loading cloud store (UbiquityStoreErrorCauseNoError).  Notifying application to refresh its UI.
>  
> 2014-09-07 19:32:11.763 MyApp[701:1803] Adding not synced store to store coordinator.
>  
> 2014-09-07 19:32:11.786 MyApp[701:1803] UbiquityStoreManager: Stores changed (UbiquityStoreErrorCauseNoError).  Notifying application to refresh its UI.
>  
> 2014-09-07 19:32:50.239 MyApp[701:5b07] -[_PFUbiquityRecordImportOperation main](734): CoreData: Ubiquity:  Error importing transaction log: <PFUbiquityTransactionLog: 0x1c115ca0>
>  
> transactionLogLocation: <PFUbiquityLocation: 0x1c116540>: /var/mobile/Library/Mobile Documents/BW24X2NM9G~my_company~MyApp/CloudLogs/BF2BD678-DA6D-411B-BB82-335692E92098/mobile~FA5A3FCC-6406-42DF-96E7-4C7196F9ECC0/BF2BD678-DA6D-411B-BB82-335692E92098/bt6j1N4YC78YESsAaQpz85haAna4EBbwn1jrfk9n0rw=/2A98EAEC-B652-4233-B15B-A5610B376772.1.cdt
>  
> transactionNumber: 1
>  
> , exception: Invalid parameter value (bad entity)
>  
>  User Info: (null)
>  
> 2014-09-07 19:32:50.253 MyApp[701:5b07] -[_PFUbiquityRecordsImporter discoverAndImportAllAvailableLogs:error:](727): CoreData: Ubiquity:  Exception while scanning for logs to import: Invalid parameter value (bad entity)
>  
> userInfo: (null)
>  
> 2014-09-07 19:32:50.269 MyApp[701:5b07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid parameter value (bad entity)'
>  
> **\* First throw call stack:
>  
> (0x2d6adf83 0x38250ccf 0x2d4c0fc7 0x2d577efd 0x2d573e11 0x2d573481 0x2d504f3b 0x2d50775b 0x2dfe25ab 0x2d5127c3 0x2d512fd1 0x2d513a2f 0x2d569ff3 0x2d560d43 0x2d55fe0f 0x2d52c60b 0x38738833 0x3873ef11 0x3873ec97 0x3873fa45 0x3873fd29 0x3887abd3 0x3887aa98)
>  
> libc++abi.dylib: terminating with uncaught exception of type NSException

I modified UbiquityStoreManager.m by adding "configuration:self.storeConfiguration" to every call of addPersistentStoreWithType:configuration:URL:options:error:
 and it worked well. Was it a good idea ? I don’t know if it was intended that the configuration specified to addPersistentStoreWithType was nil in some places, or if it was an omission.

Also, I was wondering if it’s normal that I always get 

> Will NOT migrate to cloud store from: MyAppUbiquityStore.sqlite (strategy: 2).

and that I have to wait a few seconds before seeing the following log ?

> Using local storage: 0

Thanks in advance, and thank you for providing developers with an easy way to integrate iCloud into our apps.

Kyrill
