### ISSUE TITLE
Is the LGPLv3 compatible with the App Store at all?

### ISSUE THREAD

**Issue by steipete** [lhunath/UbiquityStoreManager#4]
I know that LGPLv2 is controversial at best, lots of people say it's simply incompatible, others say that it's ok if you provide the object files for download. In general, this license is a huge PITA to work with. Is there any difference with v3? What about the Anti-DRM clauses added there?

**Comment by lhunath** [comment]
The LGPL exempts you from any anti-circumvention language in the GPL.

The LGPL requires that you accompany your object code with a mention that it uses this library and a means of accessing its license.

The LGPL requires that you release any modifications you make to this library under the same terms.

As far as I'm aware, there is no language that would inhibit App Store distribution.

**Comment by anlumo** [comment]
The third point you mention is the problem:

_The primary problem is that Apple imposes numerous legal restrictions on use and distribution of GNU Go through the iTunes Store Terms of Service, which is forbidden by section 6 of GPLv2._

http://www.fsf.org/news/2010-05-app-store-compliance

**Comment by lhunath** [comment]
The third point is easily fulfilled: Don't modify USM, or if you do, fork it on GitHub and leave the fork public.

Note that this article assumes a product bound by the GPL.  USM is not bound by the GPL.  Furthermore, GPLv3 contains relicensing language that is less restrictive with regards to "further restrictions" than the GPLv2 was.

I recommend you read the GPLv3 and LGPLv3 to see if there are any sections there that you are unsure about and quote them here.  We can then discuss them more effectively.

In the mean time, I've contacted the FSF for advise on the matter.

**Comment by steipete** [comment]
The problem is the uncertainty. Can you confirm to 100% that LGPLv3 is compatible with the App Store?

http://nmav.gnutls.org/2013/03/the-perils-of-lgplv3.html

Then there's the anti-Tivoization clause in the GPLv3, and we certainly have hardware restrictions on the iPhone.

**Comment by lhunath** [comment]
While I believe the LGPLv3 is compatible with App Store distribution, I accept that it remains somewhat unclear whether the LGPLv3 conflicts with the iTunes store terms.  Until sufficient clarity can be reached in this area, I may relicense the code under a modified version of the LGPLv3 which adds a clause that overrides any LGPLv3 language and explicitly states that should any conflicts exist, the conflicting LGPLv3 language is void.

**Comment by lhunath** [comment]
I've relicensed the code under a modified version of the LGPLv3, dubbed [LASGPLv3](../blob/master/LICENSE) at b2b987b.

**Comment by lhunath** [comment]
I've relicensed the library under the Apache License, v2, to avoid any doubt with regards to the anti-tiviolization clauses of the GPL.
