### ISSUE TITLE
Internet Connection and server side entities

### ISSUE THREAD

**Issue by ShadyGhalab** [lhunath/UbiquityStoreManager#42]
Question 1 :i want to know why failedLoadingStoreWithCause don't fire when no internet connection and willLoadStoreIsCloud still call to try to connect. when to stop ?

Question 2 : can i get the server side entities before cached in core data to perform some operations on it.

Thanks

**Comment by lhunath** [comment]
I'm having trouble understanding your questions, but I'll try to answer as best as I can.
1. The availability of the ubiquitous store is in no way dependant on an internet connection.  If there is no internet connection, Core Data will create a store on your phone but not synchronize it with the data that is in iCloud.  As soon as an internet connection becomes available, iCloud will begin synchronizing your persistence store with the other iCloud peers.
   I don't understand what you mean with "still call to try to connect", and "when to stop?".
2. You cannot get the "server side entities".  You should not think about iCloud as having a "server" and a bunch of "clients".  You certainly shouldn't think about the different iCloud peers as being individually accessible.  All you have is your store and Apple will do its best to synchronize it with the store of all the other iCloud peers.  You have no control over this process or the other peers whatsoever.
   That said, you can influence the import process of incoming changes to your store by doing something custom in your implementation of:

```
- (NSManagedObjectContext *)ubiquityStoreManager:(UbiquityStoreManager *)manager
          managedObjectContextForUbiquityChanges:(NSNotification *)note;
```
