### ISSUE TITLE
CocoaPods version tag out of date.

### ISSUE THREAD

**Issue by cgossain-showbie** [lhunath/UbiquityStoreManager#45]
I love this library and I am using cocoa pods to include it in my project, however the only version tagged is 0.1.0 which is 8 months old.

Could you please update the version tag so that I can include all the awesome updates available in the current version?

Thanks

**Comment by henneonrails** [comment]
Hi Marteen

Please just tag I will update the pods part.

Regards Holger

Am Samstag, 18. Januar 2014 schrieb cgossain-showbie :

> I love this library and I am using cocoa pods to include it in my project,
> however the only version tagged is 0.1.0 which is 8 months old.
> 
> Could you please update the version tag so that I can include all the
> awesome updates available in the current version?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lhunath/UbiquityStoreManager/issues/45
> .

## 

Holger Hänisch | Friedrich-Ebert-Str. 15 | 41539 Dormagen
02133 10605 | 0160 5579559
{ holger.haenisch@gmail.com }

**Comment by lhunath** [comment]
Pushed 1.0.0

**Comment by henneonrails** [comment]
done https://github.com/CocoaPods/Specs/issues/7048

@cgossain-showbie if you want to stay on the bleeding edge do this in your podfile:

```
pod 'UbiquityStoreManager', :head
```

**Comment by lhunath** [comment]
Thanks @henneonrails

**Comment by cgossain-showbie** [comment]
Great! I will do that. Thank you very much!
