### ISSUE TITLE
How to manually migrate store with custom migration policy?

### ISSUE THREAD

**Issue by NorbNorb** [lhunath/UbiquityStoreManager#63]
Hi,

I'm successfully using UbiquityStoreManager. Now I have to update the existing store to a newer Core Data model version. I cannot use lightweight migration and must make use of a NSEntityMigrationPolicy. I am following this tutorial which does a progressive migration (version 1 -> version 2, then version 2 -> version 3, ...) with its code:
http://www.objc.io/issue-4/core-data-migration.html
How am I supposed to integrate my custom migration policy with UbiquityStoreManager?

Thanks.

**Comment by lhunath** [comment]
You can do this from `-willLoadStoreIsCloud`
See https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/ObjC/MPAppDelegate_Store.m#L299 for how MasterPassword does it.
