### ISSUE TITLE
Constantly losing data between iPad and iPhone

### ISSUE THREAD

**Issue by fiavvek** [lhunath/UbiquityStoreManager#65]
I have used USM on a simple app I have written and it works fine (thanks!). The issue is that if I use my iPhone and enter data, the go to my iPad it doesn't show anything. When I manage to turn iCloud off then back on, it wipes the data clean off both devices...

Any idea?

**Comment by lhunath** [comment]
Please provide full UbiquityStoreManager logs of both devices, when starting for the first time, when you expect them to be in sync and when you toggle iCloud until when both devices lose all data.

**Comment by neilt** [comment]
As a point of reference, I also use it and have never had this problem.  As a matter of fact, it amazes me how well it works compared to my first attempt to use iCloud with the WWDC 2012 code.

Neil

**Comment by fiavvek** [comment]
I don't know how to get the logs to show you :(
I am using USM as it appears to do the job I want so I agree with you Neil. I must be doing something wrong on my end...

**Comment by fiavvek** [comment]
I think I need patience. All I needed to do was to wait for a few minutes instead of jumping up and down. Sorry for wasting your time.

**Comment by lhunath** [comment]
The logs should be output in your console, prefixed with [UbiquityStoreManager].  If you encounter any more issues, re-open or make a new issue with as many of these logs as possible.
