### ISSUE TITLE
Getting a lot of errors in the device console

### ISSUE THREAD

**Issue by NorbNorb** [lhunath/UbiquityStoreManager#66]
Hi,

I'm getting a lot of errors. It's always this pair:

> Jul  8 10:42:16 iPad ubd[49] <Error>: Couldn't create symlink at /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/Ubiquity/ubiquity-mmcs.log (No such file or directory)
> Jul  8 10:42:16 iPad ubd[49] <Error>: Couldn't open log file /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/Ubiquity/ubiquity-mmcs-2014-07-08-104216+0200.log (No such file or directory)

I have the feeling this pair always appears when a Core Data transaction log is read coming from iCloud.

Is this a serious error I have to react to?
Thanks.

**Comment by lhunath** [comment]
Doesn't seem to have anything to do with USM, though.  If you figure it out, definitely add some info to this issue but I'm closing this for now.
