### ISSUE TITLE
New podspec merged

### ISSUE THREAD

**Issue by henneonrails** [lhunath/UbiquityStoreManager#7]
https://github.com/CocoaPods/Specs/pull/2113

**Comment by lhunath** [comment]
You should probably update `ios.deployment_target` to `6.0`, since we use a lot of iOS 6 specific API for reliability, and I'm not even sure USM would work well if at all on iOS 5.

**Comment by henneonrails** [comment]
updated the podspec for deployment target to iOS 6.0
https://github.com/CocoaPods/Specs/commit/acd4fe1b13e35e1511659bb637fd204e716efd66
