### ISSUE TITLE
Will it be compatible with ios8?

### ISSUE THREAD

**Issue by last-Programmer** [lhunath/UbiquityStoreManager#72]
I tried to use this in ios8 beta and it seems to be that it is not working. Will it be made compaitble with ios8 when it is released?

Thank You

**Comment by lhunath** [comment]
I will not be able to invest time into investigating and possible rewriting UbiquityStoreManager for iOS 8.  At this point, I'm hoping other users of this project will be able to step up and prepare the project for adoption under iOS 8 for now.

**Comment by neilt** [comment]
According to the “What’s New in Core Data” presentation at WWDC 14 all changes to iCloud with respect to Core Data should be transparent to developers.  But a few sentences later she adds ‘provided you use the patterns presented at WWDC 13'.

To me this seems to mean that if you are using the iOS 7 APIs and not the old APIs left over from iOS 6, UbiquityStoreManager should work fine.  IIRC there are two store formats and I would guess initially that the only changes required are to deprecate the old iOS 6 stuff, which is fine with me as I do not intend to support anything less than iOS 8 for my new releases.

Maarten, would you please elaborate about what you initially think about the above statement and its impact on UbiquityStoreManager.

Thank you.
Neil

**Comment by lhunath** [comment]
From this I would assume that USM should continue to work as it did under iOS 7.  And until somebody makes an issue or comments that they're seeing iOS 8 specific problems I would assume USM is good to go on iOS 8.  No promises, though, since I haven't even tested it myself.  I don't expect the iOS 6 compatibility code in USM will be an issue either.

**Comment by neilt** [comment]
Thank you.
Neil

**Comment by last-Programmer** [comment]
I have updated the bug in this thread https://github.com/lhunath/UbiquityStoreManager/issues/73
